/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118448-g43be8d0728-20250209"
#endif /* AVUTIL_FFVERSION_H */
